# permissions for end users to edit workloadgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workloadgroup-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - workloadgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - workloadgroups/status
  verbs:
  - get
